#!/usr/bin/env bash

if [[ "$PIPELINE_DEBUG" == 1 ]]; then
  trap env EXIT
  env
  set -x
fi

. scripts/sonarqube/sonarqube_setup
. scripts/sonarqube/sonarqube_instance
. scripts/sonarqube/sonarqube_settings
. scripts/sonarqube/sonarqube_scan
